name: Build and Release Mod Manager TF2

on:
  # Déclencher les builds lors des pushes sur la branche master et des créations de tags
  push:
    tags:
      - '*'

jobs:
  # Job pour macOS
  build-mac:
    name: Build macOS
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup PHP and Composer for NativePHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'  # Version PHP compatible avec NativePHP

      - name: Install Composer
        run: |
          composer install
          composer run build:mac

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: Mod Manager TF2 macOS
          path: dist/

  # Job pour Linux
  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup PHP and Composer for NativePHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'  # Version PHP compatible avec NativePHP

      - name: Install Composer
        run: |
          composer install
          composer run build:linux

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: Mod Manager TF2 Linux
          path: dist/

  # Job pour la publication des artefacts sur GitHub Releases
  release:
    name: Create GitHub Release
    needs: [build-mac, build-linux]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/**/*.dmg
            dist/**/*.AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
