name: Build and Release Mod Manager TF2

on:
  # Déclencher les builds lors des pushes sur la branche master et des créations de tags
  push:
    tags:
      - '*'

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

  # Job pour macOS
  build-mac:
    name: Build macOS
    runs-on: macos-latest
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build for macOS
        run: npm run build -- --mac

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v2
        with:
          name: Mod Manager TF2 macOS
          path: dist/

  # Job pour Linux
  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build for Linux
        run: npm run build -- --linux

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v2
        with:
          name: Mod Manager TF2 Linux
          path: dist/

  # Job pour la publication des artefacts sur GitHub Releases
  release:
    name: Create GitHub Release
    needs: [build-mac, build-linux]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/**/*.dmg
            dist/**/*.AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}